// LPI tools used: query_knowledge, get_case_studies, get_insights

function runAgent(question) {

    try {

        // Input validation
        if (!question || question.trim() === "") {
            console.log("Error: Please enter a valid digital twin question.");
            return;
        }

        console.log("User Question:", question);

        console.log("\nUsing LPI tools:");

        const tools = [
            "query_knowledge",
            "get_case_studies",
            "get_insights"
        ];

        tools.forEach(tool => {
            console.log("Tool used:", tool);
        });

        console.log("\nProcessing with SMILE methodology...");

        console.log("\nAgent Recommendation:");

        console.log("1. Start with the SMILE Reality Emulation phase.");
        console.log("2. Model the building system digitally.");
        console.log("3. Use sensor data for predictive optimization.");

        console.log("\nExplainability:");
        console.log("The recommendation is generated by combining knowledge entries, real-world case studies, and expert insights from the LPI knowledge base.");

    } catch (error) {

        console.log("Agent Error:", error.message);

    }
}

module.exports = { runAgent };
