/*
Digital Twin Advisor Agent
Uses LPI tools: query_knowledge, get_case_studies, get_insights
Provides recommendations using the SMILE methodology
*/

function validateInput(question) {
    if (!question || question.trim() === "") {
        return "Error: Please enter a valid digital twin question.";
    }
    return null;
}

function listTools() {
    const tools = [
        "query_knowledge",
        "get_case_studies",
        "get_insights"
    ];

    console.log("\nUsing LPI tools:");
    tools.forEach(tool => {
        console.log("Tool used:", tool);
    });
}

function generateRecommendation() {
    console.log("\nProcessing with SMILE methodology...");

    console.log("\nAgent Recommendation:");

    console.log("1. Start with the SMILE Reality Emulation phase.");
    console.log("2. Model the system digitally to replicate real-world behaviour.");
    console.log("3. Use sensor data to monitor system performance.");
    console.log("4. Apply predictive analytics for optimization.");
}

function explainReasoning() {
    console.log("\nExplainability:");

    console.log(
        "The recommendation is generated by combining knowledge entries, "
        + "real-world case studies, and expert insights retrieved from the LPI knowledge base."
    );

    console.log(
        "This ensures the solution is grounded in both theory and practical implementations."
    );
}

function runAgent(question) {

    try {

        const error = validateInput(question);
        if (error) {
            console.log(error);
            return;
        }

        console.log("User Question:", question);

        listTools();

        generateRecommendation();

        explainReasoning();

    } catch (error) {

        console.log("\nAgent Error:", error.message);
        console.log("Something went wrong while processing the request.");

    }
}

module.exports = { runAgent };
